#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/
int main(){
  int i =1;
  int j=2;
  int divisors =1;
  while(1){
    for(int k=1;k<=sqrt(i);k++){
      if(i%k==0){
        divisors+=2;
      }
    }
    if(sqrt(i)*sqrt(i)!= i){
      divisors--;
    }
    if(divisors>=500)
      break;
    else
      divisors=1;
    i+=j;
    j++;

  }
  printf("%d", i);//76 576 500
  return 0;
}
