#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(){
  int term = 1;
  int new_term =0;
  int prev_term = 0;
  int sum = 0;
  while((term + prev_term)<4000000){
    new_term = term + prev_term;
    if(new_term%2==0){
      sum += new_term;
    }
    prev_term = term;
    term = new_term;
  }
  printf("%d", sum);
  return 0;
}
