#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
  4  7  10  13  16  19  22
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/
int is_pentagonal(int n, int j, int k){
  int i=(j<k ? k : j);
  int pk=1;
  while(pk<=n){
    if(pk==n)
      return 1;
    pk=(i*(3*i-1))/2;
    i++;
  }
  return 0;
}
int is_pentagonal2(int n, int j,int k){
  int i=(j<k ? k-j : j-k);
  int pk=1;
  while(pk<=n){
    if(pk==n)
      return 1;
    pk=(i*(3*i-1))/2;
    i++;
  }
  return 0;
}
int main(){
  clock_t start, end;
  double cpu_time_used;
  int pk, pj,d;
  int j = 1;
  start = clock();
  while(1){
    for(int k=1;k<j;k++){
      pk=k*(3*k-1)/2;
      if(is_pentagonal(pj+pk, j, k)&&is_pentagonal2(pj-pk, j, k)){
        d = (abs(pj-pk)<abs(pk-pj) ? abs(pj-pk) : abs(pk-pj));
        end = clock();
        cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;
        printf("%d\n", d);
        printf("cpu time used: %.2f seconds", cpu_time_used);
        return 1;
      }
    }
    pj=j*(3*j-1)/2;
    j++;
  }
  return 0;
}
