#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	  Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, 21... +1
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, 51... +3
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, 66... +4

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
int main(){
  long triangle_val;
  long pentagonal_val;
  long hexagonal_val;
  long tn = 286;
  long pn=1;
  long hn=1;
  clock_t start, end;
  double cpu_time_used;
  start = clock();
  while(1){
    triangle_val = (tn*(tn+1)/2);
    for(pn=tn/3;pn<=tn/1.33;pn++){
      pentagonal_val=(pn*(3*pn-1))/2;
      if(triangle_val==pentagonal_val){
        for(hn=tn/4;hn<tn;hn++){
          hexagonal_val = (hn*(2*hn-1));
          if(hexagonal_val==triangle_val){
            end = clock();
            printf("%ld\n", triangle_val);
            cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;
            printf("cpu time used: %.2f seconds", cpu_time_used);
            return 0;
          }
        }
      }
    }
    tn++;
  }
  return 0;
}
