#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
/*
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	P4,n=n2 	  	1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

  1.  The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
  2.  Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
  3.  This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
*/
/*NOTES
6 4-digit numbers, 12 numbers that needs pairs.

*/
int triangle(int n){
  return (n*(n+1)/2);
}
int square(int n){
  return n*n;
}
int pentagonal(int n){
  return (n*((3*n)-1))/2;
}
int hexagonal(int n){
  return n*(2*n-1);
}
int heptagonal(int n){
  return (n*((5*n)-3))/2;
}
int octagonal(int n){
  return n*(3*n-2);
}
int last2(int n){
  return n%100;
}
int first2(int n){
  return n/100;
}
int is_taken(int ar[], int counter, int length){
  for(int i=0;i<length;i++){
    if(ar[i]==counter)
      return 1;
  }
  return 0;
}
int find_pairs(int start[], int end[], int length){
  int counter=0;
  int taken_numbers[6]={-1,-1,-1,-1,-1,-1};
  int pairs[6]={-1,-1,-1,-1,-1,-1};
  int pair=0;
  int tmp[6];
  for(int i=0;i<6;i++){
    tmp[i]=end[i];
  }
  int taken_counter=0;
  for(int i=0;i<length;i++){
    counter=i+1;
    for(int j=0;j<length-1;j++){
      if(counter==6)
        counter=0;
      pair=(i+1)*10+counter+1;
      if(start[i]==tmp[counter]){
        if(is_taken(pairs,(counter+1)*10+i+1,length)&&!is_taken(taken_numbers,counter, length))
          return -1;
        pairs[i]=pair;
        tmp[counter]=-2;
        taken_numbers[i]=counter;
        taken_counter++;
        break;
      }
      counter++;
    }
  }
  return taken_counter;
}
int main(){
  // These numbers the first 4 digit number for each formulae
  int triangle_cnt=45;
  int square_cnt=32;
  int pentagonal_cnt=27;
  int hexagonal_cnt=23;
  int heptagonal_cnt=21;
  int octagonal_cnt=19;
  int tri=triangle(triangle_cnt);
  int sq=square(square_cnt);
  int pent=pentagonal(pentagonal_cnt);
  int hex=hexagonal(hexagonal_cnt);
  int hept=heptagonal(heptagonal_cnt);
  int oct=octagonal(octagonal_cnt);
  int ar_starts[6];
  int ar_ends[6];

  while(tri<10000){//i^2=100000
    printf("%d\n", sq);
    ar_starts[0]=first2(tri);
    ar_ends[0]=last2(tri);
    while(sq<10000){
      ar_starts[1]=first2(sq);
      ar_ends[1]=last2(sq);
      while(pent<10000){
        if(tri==sq)
          break;
        ar_starts[2]=first2(pent);
        ar_ends[2]=last2(pent);
        while(hex<10000){
          if(pent==sq||pent==tri)
            break;
          ar_starts[3]=first2(hex);
          ar_ends[3]=last2(hex);
          if(find_pairs(ar_starts, ar_ends,4)==0){
            break;
          }
          while(hept<10000){
            if(hex==sq||hex==tri||hex==pent)
              break;
            ar_starts[4]=first2(hept);
            ar_ends[4]=last2(hept);
            while(oct<10000){
              if(hept==sq||hept==tri||hept==pent||hept==hex)
                break;
              ar_starts[5]=first2(oct);
              ar_ends[5]=last2(oct);
              if(oct!=sq&&oct!=tri&&oct!=pent&&oct!=hex&&oct!=hept){
                if(find_pairs(ar_starts, ar_ends,6)==6){
                  goto done;
                }
              }
              oct=octagonal(++octagonal_cnt);
            }
            octagonal_cnt=19;
            oct=octagonal(octagonal_cnt);
            hept=heptagonal(++heptagonal_cnt);
          }
          heptagonal_cnt=21;
          hept=heptagonal(heptagonal_cnt);
          hex=hexagonal(++hexagonal_cnt);
        }
        hexagonal_cnt=23;
        hex=hexagonal(hexagonal_cnt);
        pent=pentagonal(++pentagonal_cnt);
      }
      pentagonal_cnt=27;
      pent=pentagonal(pentagonal_cnt);
      sq=square(++square_cnt);
    }
    square_cnt=33;
    sq=square(square_cnt);
    tri=triangle(++triangle_cnt);
  }
  printf("fuck up");
  done:
    printf("%d %d %d %d %d %d\n", tri,sq, pent, hex, hept,oct);
      printf("%d", tri+sq+pent+hex+hept+oct);
  return 0;
}
